/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void goForwardButton_click1(GButton source, GEvent event) { //_CODE_:goForwardButton:455149:
  forwardButtonClicked = true;
} //_CODE_:goForwardButton:455149:

public void goBackButton_click(GButton source, GEvent event) { //_CODE_:goBackButton:600697:
  backButtonClicked = true;
} //_CODE_:goBackButton:600697:

public void talkButton_click(GButton source, GEvent event) { //_CODE_:talkButton:931536:
  talkButtonClicked = true;
} //_CODE_:talkButton:931536:

public void miscButton1_click(GButton source, GEvent event) { //_CODE_:miscButton1:531152:
  misc1Clicked = true;
} //_CODE_:miscButton1:531152:

public void miscButton2_click(GButton source, GEvent event) { //_CODE_:miscButton2:768237:
  misc2Clicked = true;
} //_CODE_:miscButton2:768237:

public void playButton_click(GButton source, GEvent event) { //_CODE_:playButton:428500:
  playClicked = true;
} //_CODE_:playButton:428500:

public void commentButton_click(GButton source, GEvent event) { //_CODE_:commentButton:500913:
  commentButtonClicked = true;
} //_CODE_:commentButton:500913:

public void answer1Button_click(GButton source, GEvent event) { //_CODE_:answer1Button:322234:
  answer1Clicked = true;
  answerButtonClicked = true;
} //_CODE_:answer1Button:322234:

public void answer2Button_click(GButton source, GEvent event) { //_CODE_:answer2Button:306170:
  answer2Clicked = true;
  answerButtonClicked = true;
} //_CODE_:answer2Button:306170:

public void hiddenAnswerButton_click(GButton source, GEvent event) { //_CODE_:hiddenAnswerButton:206712:
  hiddenAnswerClicked = true;
  answerButtonClicked = true;
} //_CODE_:hiddenAnswerButton:206712:

public void spyglassButton_click(GButton source, GEvent event) { //_CODE_:spyglassButton:793377:
  spyglassButtonClicked = true;
} //_CODE_:spyglassButton:793377:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  goForwardButton = new GButton(this, 655, 420, 80, 30);
  goForwardButton.setText("Go Forward");
  goForwardButton.addEventHandler(this, "goForwardButton_click1");
  goBackButton = new GButton(this, 10, 420, 80, 30);
  goBackButton.setText("Go Back");
  goBackButton.addEventHandler(this, "goBackButton_click");
  talkButton = new GButton(this, 150, 400, 80, 40);
  talkButton.setText("TALK");
  talkButton.addEventHandler(this, "talkButton_click");
  miscButton1 = new GButton(this, 325, 400, 80, 40);
  miscButton1.setText("MISC1");
  miscButton1.addEventHandler(this, "miscButton1_click");
  miscButton2 = new GButton(this, 500, 400, 80, 40);
  miscButton2.setText("MISC2");
  miscButton2.addEventHandler(this, "miscButton2_click");
  playButton = new GButton(this, 325, 350, 100, 40);
  playButton.setText("PLAY");
  playButton.addEventHandler(this, "playButton_click");
  commentButton = new GButton(this, 10, 370, 80, 30);
  commentButton.setText("Mumon's Comment");
  commentButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  commentButton.addEventHandler(this, "commentButton_click");
  answer1Button = new GButton(this, 200, 285, 150, 40);
  answer1Button.setText("ANSWER 1");
  answer1Button.addEventHandler(this, "answer1Button_click");
  answer2Button = new GButton(this, 400, 285, 150, 40);
  answer2Button.setText("ANSWER 2");
  answer2Button.addEventHandler(this, "answer2Button_click");
  hiddenAnswerButton = new GButton(this, 300, 240, 150, 40);
  hiddenAnswerButton.setText("HIDDEN ANSWER");
  hiddenAnswerButton.addEventHandler(this, "hiddenAnswerButton_click");
  spyglassButton = new GButton(this, 636, 359, 100, 30);
  spyglassButton.setText("USE SPYGLASS");
  spyglassButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  spyglassButton.addEventHandler(this, "spyglassButton_click");
}

// Variable declarations 
// autogenerated do not edit
GButton goForwardButton; 
GButton goBackButton; 
GButton talkButton; 
GButton miscButton1; 
GButton miscButton2; 
GButton playButton; 
GButton commentButton; 
GButton answer1Button; 
GButton answer2Button; 
GButton hiddenAnswerButton; 
GButton spyglassButton; 
